// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOCW4LfXi1gTSOpHA0hRDMbOUXMABKI40',
    appId: '1:736708833593:web:0f3a7f3f8f196a90fa38e8',
    messagingSenderId: '736708833593',
    projectId: 'bar-health',
    authDomain: 'bar-health.firebaseapp.com',
    storageBucket: 'bar-health.firebasestorage.app',
    measurementId: 'G-X032SSKWMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWeMmS0QP3QYi-4gk5Kn4NO9XGnL9kf9E',
    appId: '1:736708833593:android:aa4ffb6df9aff6f1fa38e8',
    messagingSenderId: '736708833593',
    projectId: 'bar-health',
    storageBucket: 'bar-health.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOCW4LfXi1gTSOpHA0hRDMbOUXMABKI40',
    appId: '1:736708833593:web:4e47ecf0736a99d2fa38e8',
    messagingSenderId: '736708833593',
    projectId: 'bar-health',
    authDomain: 'bar-health.firebaseapp.com',
    storageBucket: 'bar-health.firebasestorage.app',
    measurementId: 'G-WZJC8B9YJE',
  );
}
