// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_H0EyCARE4qq3b4McQSxw1CaP1VV-Zk',
    appId: '1:145172120250:android:fd9b7aec1f83347f313883',
    messagingSenderId: '145172120250',
    projectId: 'flutter-lab-project-app',
    storageBucket: 'flutter-lab-project-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIU6HZR1bQg6xGRHnpGvYaNEI6YvN4qpA',
    appId: '1:145172120250:ios:4be416c8ccbc0704313883',
    messagingSenderId: '145172120250',
    projectId: 'flutter-lab-project-app',
    storageBucket: 'flutter-lab-project-app.firebasestorage.app',
    androidClientId: '145172120250-70obl6ue5cg492tb9mif4dsefmafc6ei.apps.googleusercontent.com',
    iosClientId: '145172120250-j4e2vhdo34l6hr3hmm8acc0h5hvbvjve.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}