name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # لا تنشر المشروع إلى pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # حزمة إعادة تسمية التطبيق (لتغيير الاسم من الكود)
  rename: ^3.1.0

  # حزمة لتوليد أيقونة التطبيق
  flutter_launcher_icons: ^0.14.3

  # حزمة شاشة البداية Splash (اختيارية حالياً)
  flutter_native_splash: ^2.3.11

# ----------------------------------------------------------------------
# إعداد أيقونة التطبيق (App Icon)
# ----------------------------------------------------------------------
flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true # لتجنب مشاكل متجر Apple

# ----------------------------------------------------------------------
# إعداد شاشة البداية (Splash Screen)
# ----------------------------------------------------------------------
# تم الإلغاء مؤقتاً لأنك تستخدم تصميم مخصص داخل AndroidManifest
# flutter_native_splash:
#   image: assets/images/logo.png
#   color: "#FFFFFF"
#   android_12:
#     image: assets/images/logo.png
#     color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png

